In [1]:
#Don't mind this box
import os
import pandas as pd
# Retrieve current working directory (`cwd`)
cwd = os.getcwd()
cwd

# Change directory 
os.chdir("/Users/alex/Desktop/vodafone")

# List all files and directories in current directory
#os.listdir('.')

In [3]:
#Very simple version of Random forest
df=pd.read_csv('data_train1.csv')
df=df.drop(['Store_ID'],axis=1)
X=df.iloc[:,:-1].values
y=df['Footfall_classif'].values

In [4]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

In [5]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=20, random_state=0)  
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)  

In [6]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))  

[[21  0  0]
 [ 4 24  1]
 [ 0  1 14]]
             precision    recall  f1-score   support

          0       0.84      1.00      0.91        21
          1       0.96      0.83      0.89        29
          2       0.93      0.93      0.93        15

avg / total       0.92      0.91      0.91        65

0.907692307692


In [7]:
accuracy = accuracy_score(y_test,y_pred)
print('accuracy = ',accuracy)

accuracy =  0.907692307692


In [8]:
print(y_pred)
print('\n')
print(y_test)

[1 1 0 0 1 1 0 2 0 2 2 2 1 1 0 0 1 0 2 1 2 0 1 1 0 1 0 2 1 2 1 1 2 0 0 1 1
 0 0 0 1 0 0 0 0 2 2 1 0 1 1 0 0 1 0 2 1 0 0 2 1 1 2 1 2]


[1 1 0 0 1 1 0 2 0 2 2 2 1 1 0 0 2 0 2 1 2 0 1 1 0 1 1 2 1 2 1 1 1 1 0 1 1
 0 0 0 1 0 0 0 0 2 2 1 1 1 1 0 1 1 0 2 1 0 0 2 1 1 2 1 2]
